# Generated by Django 5.1.6 on 2025-10-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='One GIS-Powered Console for Smarter Councils.', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Optional supporting text below the title.')),
                ('cta_primary_label', models.CharField(default='Book a Demo', max_length=60)),
                ('cta_primary_href', models.CharField(default='#', max_length=255)),
                ('cta_secondary_label', models.CharField(blank=True, default='See Live Sandbox', max_length=60)),
                ('cta_secondary_href', models.CharField(blank=True, default='#', max_length=255)),
                ('bg_type', models.CharField(choices=[('pattern', 'Subtle Pattern'), ('image', 'Background Image'), ('solid', 'Solid Color')], default='pattern', max_length=20)),
                ('bg_media', models.ImageField(blank=True, help_text='Optional background image.', null=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one hero should be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['-created_at'],
            },
        ),
    ]
