# Generated by Django 5.1.6 on 2025-10-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Partner or organization name.', max_length=100)),
                ('image', models.ImageField(help_text='Logo image to display on the landing page.', upload_to='trust_logos/')),
                ('link', models.URLField(blank=True, help_text='Optional link to the partner’s website.', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the page.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether the logo appears on the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trust Logo',
                'verbose_name_plural': 'Trust Logos',
                'ordering': ['order'],
            },
        ),
    ]
