# Generated by Django 5.1.6 on 2025-11-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_trustlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Short description of the KPI (e.g. 'Faster Permit Approvals').", max_length=100)),
                ('value', models.CharField(help_text="Numeric or symbolic KPI value (e.g. '30%', '15M+', '4.9/5').", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the KPI grid.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this KPI is visible.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI Statistic',
                'verbose_name_plural': 'KPI Statistics',
                'ordering': ['order'],
            },
        ),
    ]
