# Generated by Django 5.1.6 on 2025-11-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_kpistat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Material icon name (e.g., 'map', 'engineering', 'emergency_home').", max_length=60)),
                ('title', models.CharField(help_text='Solution title.', max_length=150)),
                ('description', models.TextField(help_text='Short description of what this solution offers.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the frontend.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility on the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
                'ordering': ['order'],
            },
        ),
    ]
