# Generated by Django 5.1.6 on 2025-11-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tag name (e.g., 'Permit Management', 'Code Enforcement').", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the tag name.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional short description for this tag.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for the frontend.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether the tag is visible or selectable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Use Case Tag',
                'verbose_name_plural': 'Use Case Tags',
                'ordering': ['order', 'name'],
            },
        ),
    ]
