# Generated by Django 5.1.6 on 2025-11-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_usecasetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCaseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Feature title (e.g., 'Streamline Permit Approvals').", max_length=150)),
                ('description', models.TextField(help_text='Detailed explanation of how this feature solves a real-world challenge.')),
                ('image', models.ImageField(blank=True, help_text='Optional image illustrating the feature.', null=True, upload_to='use_cases/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the frontend.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility on the landing page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with this feature.', related_name='features', to='cms.usecasetag')),
            ],
            options={
                'verbose_name': 'Use Case Feature',
                'verbose_name_plural': 'Use Case Features',
                'ordering': ['order'],
            },
        ),
    ]
