# Generated by Django 5.2.7 on 2025-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_usecasefeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Main image illustrating the case study.', upload_to='case_studies/')),
                ('category', models.CharField(help_text="Category label (e.g., 'Traffic Flow', 'Public Safety').", max_length=100)),
                ('city', models.CharField(help_text="City or organization name (e.g., 'Metropolis').", max_length=100)),
                ('title', models.CharField(help_text="Title summarizing the key outcome (e.g., '20% Congestion Reduction').", max_length=200)),
                ('summary', models.TextField(help_text='Short paragraph describing the results and how they were achieved.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the grid.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility on the landing page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order'],
            },
        ),
    ]
