# Generated by Django 5.2.7 on 2025-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_casestudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlimpseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image file showing part of the platform UI.', upload_to='glimpse/')),
                ('title', models.CharField(blank=True, help_text='Optional short title or label for the image.', max_length=150)),
                ('caption', models.CharField(blank=True, help_text='Optional short caption describing the image.', max_length=250)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the frontend grid.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility on the landing page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Glimpse Image',
                'verbose_name_plural': 'Glimpse Images',
                'ordering': ['order'],
            },
        ),
    ]
