# Generated by Django 5.2.7 on 2025-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_glimpseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Integration name (e.g., 'Esri', 'Salesforce').", max_length=100)),
                ('logo', models.ImageField(help_text='Logo image representing the integration.', upload_to='integrations/')),
                ('website_url', models.URLField(blank=True, help_text='Optional URL to the partner or product page.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the integrations grid.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this integration is visible.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'ordering': ['order', 'name'],
            },
        ),
    ]
