# Generated by Django 5.2.7 on 2025-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('essentials', 'Essentials'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], help_text="Plan name or tier (e.g., Essentials, Professional, Enterprise).", max_length=100, unique=True)),
                ('description', models.CharField(help_text='Short description of the plan’s target audience.', max_length=255)),
                ('price', models.CharField(help_text="Displayed price (e.g., '$499/mo' or 'Contact Us').", max_length=50)),
                ('highlight', models.BooleanField(default=False, help_text="Marks this plan as 'Most Popular'.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for frontend rendering.')),
                ('features', models.JSONField(default=list, help_text='List of included features.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether the plan is visible on the pricing section.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order'],
            },
        ),
    ]
