# Generated by Django 5.2.7 on 2025-01-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Short description of the feature.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the plan.')),
                ('included', models.BooleanField(default=True, help_text='Indicates if the feature is included or optional.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='The pricing plan this feature belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='cms.pricingplan')),
            ],
            options={
                'verbose_name': 'Pricing Feature',
                'verbose_name_plural': 'Pricing Features',
                'ordering': ['plan', 'order'],
            },
        ),
    ]
