# Generated by Django 5.2.7 on 2025-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_pricingfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='Quoted testimonial text.')),
                ('author_name', models.CharField(help_text='Full name of the testimonial author.', max_length=100)),
                ('author_title', models.CharField(help_text="Author’s title or role (e.g., 'City Planner').", max_length=150)),
                ('organization', models.CharField(help_text='Name of the organization or department.', max_length=150)),
                ('author_photo', models.ImageField(blank=True, help_text='Optional author photo.', null=True, upload_to='testimonials/')),
                ('verified', models.BooleanField(default=True, help_text='Mark if testimonial is verified.')),
                ('stat_1_label', models.CharField(blank=True, help_text="Optional label for the first impact metric (e.g., 'Faster Reviews').", max_length=50)),
                ('stat_1_value', models.CharField(blank=True, help_text="Numeric/statistical value for the first metric (e.g., '50%').", max_length=50)),
                ('stat_2_label', models.CharField(blank=True, help_text="Optional label for the second impact metric (e.g., 'Productivity Boost').", max_length=50)),
                ('stat_2_value', models.CharField(blank=True, help_text="Numeric/statistical value for the second metric (e.g., '20%').", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the frontend.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility on the landing page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
    ]
