# Generated by Django 5.2.7 on 2025-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_faqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text="Main headline for the final CTA (e.g., 'Ready to Build a Smarter Council?').", max_length=200)),
                ('subheading', models.TextField(help_text='Supporting text that elaborates the CTA purpose.')),
                ('primary_button_text', models.CharField(default='Book Your Free Demo', help_text='Text for the main button.', max_length=100)),
                ('primary_button_url', models.URLField(blank=True, help_text='URL the primary button links to.')),
                ('secondary_button_text', models.CharField(blank=True, help_text='Optional text for a secondary button.', max_length=100)),
                ('secondary_button_url', models.URLField(blank=True, help_text='URL the secondary button links to.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order if multiple CTAs exist.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this CTA section is visible.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Final CTA',
                'verbose_name_plural': 'Final CTAs',
                'ordering': ['order'],
            },
        ),
    ]
