# Generated by Django 5.2.7 on 2025-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_finalcta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the footer link group (e.g., 'Product').", max_length=100)),
                ('links', models.JSONField(default=list, help_text="List of link objects, each with 'label' and 'url'.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for footer link groups.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility in the footer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Link Group',
                'verbose_name_plural': 'Footer Link Groups',
                'ordering': ['order'],
            },
        ),
    ]
