# Generated by Django 5.2.7 on 2025-01-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_footerlinkgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Link label displayed in the footer (e.g., 'Privacy Policy').", max_length=100)),
                ('url', models.URLField(help_text='URL the footer link points to.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the footer group.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility of this link.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(help_text='Parent link group (e.g., Product, Company, Legal).', on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='cms.footerlinkgroup')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['order'],
            },
        ),
    ]
