name: "Fixture Agent"
description: "Generates and manages Django fixture data for CMS models."
author: "Codex Assistant"
language: "python"
runtime: "django"
capabilities:
  - create_json_fixtures
  - load_json_fixtures
  - update_fixtures
  - verify_fixture_integrity
triggers:
  - pattern: "fixtures"
  - pattern: "initial data"
  - pattern: "mock data"
permissions:
  filesystem: write
  network: restricted
  database: read
tasks:
  - id: "create_fixture"
    description: "Generate fixture JSON with starter content."
    command: "python manage.py dumpdata cms --indent 2 > cms/fixtures/initial_cms_data.json"
  - id: "load_fixture"
    description: "Load fixture data into the database."
    command: "python manage.py loaddata cms/fixtures/initial_cms_data.json"
  - id: "verify_fixture"
    description: "Check fixture validity and required fields."
    command: "python manage.py check"
